version: "3"
services:
  app:
    build:
      context: ./app  # Dockerfileのあるディレクトリを指定します
    ports:
      - "3000:3000"
      - "12000:8080"
    volumes:
      - ./app:/app  # ボリュームのマウント先を変更します
      - node_modules:/app/node_modules
    command: sh -c "npm run dev"
    networks:
      - nextjs_web_app

networks:
  nextjs_web_app:
    driver: bridge

volumes:
  node_modules:
